#**Numpy**
Numpy is a powerful library for scientific computation in Python. Its main object is a multi-dimensional array of **numbers** and it provides fast routines for mathematical operations, sorting, selection, shape manipulation, linear algebra and statistical simulation.

Let us try to write a code which multiplies the corresponding elements in 2 lists in native python

In [36]:
# multiply the corresponding elements in 2 lists
bar = [1,2,3]
foo = [4,5,6]
barfoo = []
for i in range(len(bar)):
  barfoo.append(bar[i]*foo[i])
print(barfoo)

[4, 10, 18]


The above example is very inefficient as the multiplications are done sequentially. Numpy does the multiplications in parallel at near C speeds.

In [37]:
import numpy as np
bar = np.array([1,2,3])
foo = np.array([4,5,6])
barfoo = bar*foo
print(barfoo)

[ 4 10 18]


Let us try to time both codes for 2 large arrays using Python built-in time library

In [38]:
from time import time
import numpy as np
bar = list(range(1,100000))
foo = list(range(1,100000))
barfoo = []
start = time()
for i in range(len(bar)):
  barfoo.append(bar[i]*foo[i])
end = time()
print('Elapsed time in case of Looping:',1000*(end-start),'ms')
bar = np.array(bar)
foo = np.array(foo)
start = time()  
barfoo = bar*foo
end = time()
print('Elapsed time using NumPy:',1000*(end-start),'ms')

Elapsed time in case of Looping: 24.222373962402344 ms
Elapsed time using NumPy: 1.855611801147461 ms


Array Creation

In [ ]:
import numpy as np
a = np.array([4,1,3]) 
#print(a,type(a))
a = np.array([[1,2,3],[4,5,6]],dtype='float')
#print(a,type(a))
a = np.linspace(0,100,10)
#print(a)
a = np.arange(0,100,10)
# print(a)
a = np.zeros((3,5),dtype='int')
#print(a)
a = np.ones((2,4),dtype='float')
#print(a)
a = np.empty((3,4,3))
#print(a)
a = np.eye(3)
print(a)

Numpy arrays have 6 attributes:


*   **shape** is the dimensions of the array.
*   **ndim** is the number of dimensions of the array.
*   **size** is the number of elements in the array.
*   **dtype** is the type of elements in the array
*   **itemsize** is the size of an element in the array in bytes
*   **data** is a buffer which contains the elements of the array. But, this attribute is rarely used as we access array elements using indexing



In [55]:
a = np.arange(2,12,1)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.data[1])

[ 2  3  4  5  6  7  8  9 10 11]
(10,)
1
10
8
int64
3


Indexing Numpy Arrays is so similar to MATLAB

In [ ]:
a = np.array([[4,3,1],[2,1,2],[4,7,3]])
print(a)
#print(a[0,1])
#print(a[1,:])
#print(a[:,0])
ix = np.array([1,1,0],dtype='bool')
print(a[:,ix]) # supports logical indexing (it comes in handy in plenty of situations)

Arithmetic operators on arrays apply element-wise

In [62]:
a = np.array([1,2,3])
b = np.array([2,4,6])
print(a-b)
print(a+b)
print(a*b)
print(a**b)
print(a/b)

[-1 -2 -3]
[3 6 9]
[ 2  8 18]
[  1  16 729]
[0.5 0.5 0.5]


Arrays support many unary operations

In [64]:
a = np.arange(0,11,2).reshape((2,-1))
print(a)
print('Sum of array elements: ',a.sum())
print('Array maximum: ',a.max())
print('Array minimum: ',a.min())
print('Array mean: ',a.mean())

[[ 0  2  4]
 [ 6  8 10]]
Sum of array elements:  30
Array maximum:  10
Array minimum:  0
Array mean:  5.0


Numpy supports universal functions that are applied element-wise to array elements

In [65]:
a = np.arange(0,11,1)
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.sin(a)**2+np.cos(a)**2)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Shape Manipulation

*   **Reshape** function returns its argument with a modified shape
*   **Resize** function modifies the array itself



In [71]:
a = np.arange(5,20,1)
#print(a.reshape(3,5))
#print(a) # The array 'a' hasn't changed after calling reshape
print(a.resize(3,5))
#print(a) # The array 'a' changed after calling resize
#print(a.reshape(5,-1)) # using -1 in the shape tuple automatically calculates the other dimension
print(a.T) #transpose the array a
print(a.ravel())

None
[[ 5 10 15]
 [ 6 11 16]
 [ 7 12 17]
 [ 8 13 18]
 [ 9 14 19]]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Splitting and Stacking arrays


In [74]:
a = np.ones((2,5))
b = np.zeros((2,3))
c = np.hstack((a,b)) # horizontally stacks the two arrays
#print(c,c.shape)
d = np.vstack((c,-np.ones((3,8)))) # vertically stacks the two arrays
print(d,d.shape)

[[ 1.  1.  1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]] (5, 8)


In [77]:
c,x = np.vsplit(d,(2,)) # split after the 2nd row
#print(c,x)
a,b = np.hsplit(c,(5,)) # split after the 5th column
print(a)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


Copying numpy arrays

In [79]:
a = np.ones((2,3))
b = a # shallow copy
#print(b is a)
b = a.copy() # deep copy
print(b is a)

False


In [83]:
a = np.ones((2,3))
b = a.copy() # shallow copy
b[0,0] = 0
print(a,b)

[[1. 1. 1.]
 [1. 1. 1.]] [[0. 1. 1.]
 [1. 1. 1.]]


#**Classes**
As we have discussed, *everything* is an object in Python. Objects are, as you may know, instantiations of *classes* and, as you may have already guessed, you can indeed define your own classes.
###This section was prepared by Eng. Muhammad Al Aref

In [84]:
class MyClass:
      
    class_variable = [1, 2, 3]
    
    def __init__(self):
        print('I am the constructor!')
        self.variable = 'I am an object variable'
        self._variable = 'I am a private object variable'
    
    def my_method(self):
        print('I am a method!')
    
    def my_returning_method(self, something):
        return something
    
    def my_variable_returning_method(self):
        return self._variable
    
    def _my_private_method(self):
        print('I am a private method and I "should" not be called from outside the class')
        
    @classmethod
    def my_class_method(cls):
        print('I am a class method and I implicitly get my class as my first argument:', cls)
        
    @staticmethod
    def my_static_method():
        print('I am a class method and I behave just like any normal method, just call me from my class!')

In [94]:
print(MyClass)
my_class_instance = MyClass()
print(my_class_instance)
my_class_instance.my_method()
print(my_class_instance.my_returning_method('I am the something!'))
print(my_class_instance.my_variable_returning_method())
print(my_class_instance.variable)
my_class_instance._my_private_method()  # while you can, you "shouldn't" do that
print(my_class_instance._variable)   # again, you can but you shouldn't
print(MyClass.class_variable)
MyClass.my_class_method()             # you can it from my_class_instance as well, but... you shouldn't
MyClass.my_static_method()            # again, you can it from my_class_instance as well, but?

<class '__main__.MyClass'>
I am the constructor!
I am a method!
I am the something!
I am a private object variable
I am an object variable
I am a private method and I "should" not be called from outside the class
I am a private object variable
[1, 2, 3]
I am a class method and I implicitly get my class as my first argument: <class '__main__.MyClass'>
I am a class method and I behave just like any normal method, just call me from my class!


##Inheritance

A class can inherit from another class. In effect, that gives the *child* class all the functionality of the *parent* class. *Child* classes can *override* some of these functionalities if needed.

In [95]:
class MyOtherClass(MyClass):
    
    def my_method(self):
            print("I am overriding my parent's method")
        
    def my_brand_new_method(self):
        print("I am not inherited")

In [97]:
print(MyOtherClass)
my_other_instance = MyOtherClass()
print(my_other_instance)
my_other_instance.my_method()
my_other_instance.my_brand_new_method()
print(my_other_instance.my_returning_method('I am the something!'))
print(my_other_instance.my_variable_returning_method())
print(my_other_instance.variable)
MyOtherClass.my_class_method()
MyOtherClass.my_static_method()

<class '__main__.MyOtherClass'>
I am the constructor!
I am overriding my parent's method
I am not inherited
I am the something!
I am a private object variable
I am an object variable
I am a class method and I implicitly get my class as my first argument: <class '__main__.MyOtherClass'>
I am a class method and I behave just like any normal method, just call me from my class!
